name: Account activity

on:
  # schedule:
  # Every 30 mins
    # - cron: '0,30 * * * *'

  workflow_dispatch:

jobs:
  update_activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run fetch/update script
        run: python3 fetch.py

      - name: Display updated readme (test)
        run: cat README.md