name: Dynamic README Event Log

on:
  schedule:
    # Every 30 mins
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  update_activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repository
        uses: actions/checkout@v3

      - name: Install Python dependencies and run Fetch / README update scripts
        run: |
          cd .github/workflows
          pip install -r requirements.txt
          python3 fetch.py
          python3 blogfetch.py

      - name: (DEBUG) Print README changes
        run: cat README.md
      
      - name: Commit updated README
        run: |
          if [ ! -z "$(git status -s)" ]; 
          then
          git config user.name "Github Action Runner"
          git config user.email "github-actions@github.com"
          git status
          git add README.md
          git commit -m "[GITHUB ACTION] Refreshed history in README ($(date))"
          git push
          else
          echo "There's no changes to the readme - will not attempt commit"
          fi
